export 'global_information/global_information.dart';
export 'notices/notices.dart';
export 'personal/personal.dart';
export 'privacy/privacy.dart';
export 'profile/profile.dart';
export 'recovery/recovery.dart';
export 'support/support.dart';
export 'terms/terms.dart';
export 'theme/theme.dart';
