name: altme

on: [ pull_request, push ]

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "**/*_observer.dart **/change.dart"
      flutter_channel: stable
      flutter_version: 2.10.0
      min_coverage: 95
